export enum Building {
  forest = "forest",
  village = "village",
  watchTower = "watchTower",
  stoneWatchTower = "stoneWatchTower",
  castle = "castle",
  gathererCamp = "gathererCamp",
  druidHut = "druidHut",
  school = "school",
  barn = "barn",
  farm = "farm",
  sawmill = "sawmill",
  coalMine = "coalMine",
  stoneMine = "stoneMine",
  windmill = "windmill",
  coalDeposite = "coalDeposite",
  lighthouse = "lighthouse",
  factory = "factory",
  plankFactory = "plankFactory",
  brickFactory = "brickFactory",
  powerfarm = "powerfarm",
  woodPlant = "woodPlant",
  coalPlant = "coalPlant",
  rocketSilo = "rocketSilo",
}
