export enum Job {
    default = 'default',
    berryGatherer = 'berryGatherer',
    woodGatherer = 'woodGatherer',
    explorer = 'explorer',
    druid = 'druid',
    farmer = 'farmer',
    stoneGatherer = 'stoneGatherer',
    lumberjack = 'lumberjack',
    coalMiner = 'coalMiner',
    stoneMiner = 'stoneMiner',
    limestoneMiner = 'limestoneMiner',
    limestoneBrickWorker = 'limestoneBrickWorker',
    coalStationEngineer = 'coalStationEngineer',
}